version: '3'
services:
  database:
    image: postgis/postgis:14-master
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus-backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cache:
    image: redis:6
    restart: unless-stopped
    networks:
      - directus-backend

  directus:
    image: directus/directus:10
    restart: unless-stopped
    ports:
      - 127.0.0.1:8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./data/uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus-backend
      - default
    depends_on:
      - cache
      - database
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: database
      DB_PORT: '5432'
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: 'cache'
      REDIS_PORT: 6379

      CACHE_STORE: 'redis'
      ASSETS_CACHE_TTL: '10d'
      CACHE_TTL: '10s'
      RATE_LIMITER_STORE: 'redis'
      SYNCHRONIZATION_STORE: 'redis'
      MESSENGER_STORE: 'redis'
      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'false'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: ${PUBLIC_URL}
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}

      LOG_LEVEL: ${LOG_LEVEL}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8055/server/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      args:
        - BACKEND_BASE=${PUBLIC_URL}
    restart: unless-stopped
    ports:
      - 127.0.0.1:4173:80
    depends_on:
      - directus
  frontend-dev:
    build:
      context: .
      args:
        - BACKEND_BASE=${PUBLIC_URL}
      target: dev
    depends_on:
      - directus
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:5173:5173
    command:
      - ash
      - -c
      - yarn && yarn dev --host 0.0.0.0

networks:
  default:
  directus-backend:
